language: node_js

node_js:
- 7

before_script:
- psql -c 'create database "rocketleaguesam-test";' -U postgres

script:
- npm run all

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
  - node_modules

services:
  - postgresql